name: tool_rental_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  firebase_analytics: ^11.6.0
  google_fonts: ^6.3.1
  image_picker: ^1.1.2
  provider: ^6.1.2

  shared_preferences: ^2.2.0
  url_launcher: ^6.1.10
  intl: ^0.18.1 # Or the latest version


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/Logo.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/Logo.png
    - lib/assets/Categories/
