// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr0sVwUsCO4cC592mwotr-2L7E_dR9tCU',
    appId: '1:374274699833:web:fb9adb915e21997cab53e8',
    messagingSenderId: '374274699833',
    projectId: 'tools-rental-46a41',
    authDomain: 'tools-rental-46a41.firebaseapp.com',
    storageBucket: 'tools-rental-46a41.firebasestorage.app',
    measurementId: 'G-990Z8ZK9W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuMBNAA0m2alVmW5_pnRwDQqaci6gTI34',
    appId: '1:374274699833:android:1b6c7ab5699f4fccab53e8',
    messagingSenderId: '374274699833',
    projectId: 'tools-rental-46a41',
    storageBucket: 'tools-rental-46a41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAvvNZr-3RrHI02NY6G76xjSw3IelF9Xc',
    appId: '1:374274699833:ios:5500e42f9cfc65e2ab53e8',
    messagingSenderId: '374274699833',
    projectId: 'tools-rental-46a41',
    storageBucket: 'tools-rental-46a41.firebasestorage.app',
    iosBundleId: 'com.example.toolRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAvvNZr-3RrHI02NY6G76xjSw3IelF9Xc',
    appId: '1:374274699833:ios:5500e42f9cfc65e2ab53e8',
    messagingSenderId: '374274699833',
    projectId: 'tools-rental-46a41',
    storageBucket: 'tools-rental-46a41.firebasestorage.app',
    iosBundleId: 'com.example.toolRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr0sVwUsCO4cC592mwotr-2L7E_dR9tCU',
    appId: '1:374274699833:web:73a7a94f0ea8d9c7ab53e8',
    messagingSenderId: '374274699833',
    projectId: 'tools-rental-46a41',
    authDomain: 'tools-rental-46a41.firebaseapp.com',
    storageBucket: 'tools-rental-46a41.firebasestorage.app',
    measurementId: 'G-381W0Q2FKS',
  );
}
